spring.application.name=order-service

server.port=8106

#DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce-microservices
spring.datasource.username=postgres
spring.datasource.password=sisu

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Actuator(Expose all endpoint in local to test, but in production we expose only "health,beans,logger,metrics,info" for security reason)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
#management.endpoint.shutdown.enabled=true

#Customize actuator "info" endpoint
info.app.name=This is Order Service
info.app.description=This is ecomm project build by us
info.app.version=3.5.13


#EUREKA ENABLE
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#Log file
logging.file.name=logs/order-service.log
logging.level.root=INFO
logging.level.com.niranjana=DEBUG

#CircuitBreaker
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.sliding-window-size=5
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.cartService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.cartService.sliding-window-size=5
resilience4j.circuitbreaker.instances.cartService.wait-duration-in-open-state=10s

# Enable logging for the Feign interface
logging.level.com.niranjana.ecommerce.order.client.UserServiceClient=DEBUG
logging.level.com.niranjana.ecommerce.order.client.ProductClient=DEBUG
logging.level.com.niranjana.ecommerce.order.client.CartServiceClient=DEBUG
logging.level.com.niranjana.ecommerce.order.client.PaymentClient=DEBUG

# ===== Kafka Config =====
spring.kafka.bootstrap-servers=localhost:9092

#==========Producer==============
#ignores producer class name mismatch
spring.kafka.producer.properties.spring.json.add.type.headers=false


# ==================# -------- CONSUMER (from order-topic) --------===============
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#FIX HERE(allows both order + inventory DTOs)
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# optional safety fix (avoids class mismatch)
spring.kafka.consumer.properties.spring.json.use.type.headers=false


#Order Producer Own Topic
kafka.topic.order-created=order-topic-microservices-producer

#Order Consumer Consume Topics From Producer(Payment)
kafka.topic.payment-success=payment-success
kafka.topic.payment-failed=payment-failed




